/**
 * Fältformulär för modellerna — mallarna som återkommer en gång per föreläsning.
 *
 * U-kurvan, nästa-ord-demon, sykofantispegeln, friktionskartan … Var och en står
 * på en enda slide i ett deck, men i tio, tjugo, trettio deck. Joel flyttar dem
 * mellan föreläsningar och byter exempel efter publik: kommunen blir skolan,
 * ekonomen blir läraren. Då är det texterna han vill åt, och de hade bara
 * härledda formulär med engelska fältnamn.
 *
 * Samma konventioner som template-schemas-vanliga.ts (se docs/FALTFORMULAR.md).
 * Ren modul.
 */

import type { TemplateSchema } from "./template-schemas";
import { accent, background, chapter, darken, kicker, overlay } from "./template-schema-fields.ts";

export const modelTemplateSchemas: Record<string, TemplateSchema> = {
  UCurveChart: {
    name: "UCurveChart",
    description: "U-kurvan: halvhjärtad AI-användning ger sämre resultat än ingen alls. Kurvan ritas upp över tre zoner som beskrivs en i taget.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "subtitle", label: "Underrubrik eller källa", type: "multiline" },
      chapter,
      { name: "xLabel", label: "X-axelns namn", type: "text", placeholder: "AI-användning →" },
      { name: "yLabel", label: "Y-axelns namn", type: "text", placeholder: "Kvalitet →" },
      { name: "xMinLabel", label: "Vid x-axelns början", type: "text", placeholder: "Ingen", advanced: true },
      { name: "xMaxLabel", label: "Vid x-axelns slut", type: "text", placeholder: "Omfattande", advanced: true },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Zonerna längs kurvan",
    contentHint: "En rad per zon, från vänster till höger: - namn · ton · beskrivning. Ton: neutral, danger eller success. **fet** = accentfärg.",
    defaultContent:
      "\n- Ingen AI · neutral · Långsamt, men du äger varje del\n- Halvhjärtad · danger · Första utkastet utan eftertanke. **Sämst utfall.**\n- Engagerad · success · AI gör grovjobbet, du gör bedömningen\n",
  },

  NextTokenDemo: {
    name: "NextTokenDemo",
    description: "Så väljer en språkmodell nästa ord: meningen byggs upp ord för ord, med kandidaterna och deras sannolikheter svävande över markören.",
    fields: [
      { name: "bridge", label: "Bryggan före demon", type: "text", placeholder: "Hur **gör** den det?", hint: "Stor text på första klicket. **fet** = accentfärg." },
      { name: "prefix", label: "Början på meningen", type: "text", required: true, placeholder: "En skola är" },
      {
        name: "decisionsText",
        label: "Orden modellen väljer mellan",
        type: "multiline",
        placeholder: "en:0.41,ett:0.22,det:0.14 / plats:0.52,byggnad:0.31",
        hint: "Ett val per ord i meningen, skilda med /. I varje val: ord:sannolikhet med komma emellan. Det första ordet vinner och läggs till meningen.",
      },
      { name: "closing", label: "Slutsatsen", type: "multiline", hint: "Visas när meningen är färdig." },
      chapter,
      {
        name: "decisions",
        label: "Valen som lista (i stället för texten ovan)",
        type: "json",
        advanced: true,
        placeholder: '[\n  [["en", 0.41], ["ett", 0.22]]\n]',
      },
      accent,
      background,
      overlay(),
    ],
    hasContent: false,
  },

  SycophancyMirror: {
    name: "SycophancyMirror",
    description: "Samma fråga ställd två gånger — självsäkert och osäkert — och två olika svar. Visar att modellen följer tonen, inte fakta.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "confidentUser", label: "Frågan, självsäkert ställd", type: "multiline", required: true, placeholder: "Jag har rätt, eller hur?" },
      { name: "confidentAi", label: "AI:ns svar på den självsäkra", type: "multiline", required: true, placeholder: "Svaret som håller med." },
      { name: "insecureUser", label: "Samma fråga, osäkert ställd", type: "multiline", required: true, placeholder: "Har jag fel här?" },
      { name: "insecureAi", label: "AI:ns svar på den osäkra", type: "multiline", required: true, placeholder: "Svaret som nyanserar." },
      { name: "punchline", label: "Slutraden under båda", type: "multiline", placeholder: "Samma fråga. Samma fakta. Bara olika ton.", hint: "**fet** = accentfärg." },
      { name: "projector", label: "Visa svaren med separata klick", type: "boolean", default: false, advanced: true, hint: "Projektorläget låter clickern visa svaren stegvis." },
      kicker,
      chapter,
    ],
    hasContent: false,
  },

  HumanCapacities: {
    name: "HumanCapacities",
    description: "Tre eller fyra förmågor som stora kort i rad. Varje klick lyfter fram ett kort och dämpar de andra. Byggd för avslutningen: det människan bär.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      chapter,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Korten",
    contentHint: "En rad per kort, tre eller fyra: - ordet · raden under.",
    defaultContent: "\n- Omdöme · Att veta när svaret inte räcker.\n- Relation · Att någon faktiskt ser dig.\n- Ansvar · Att stå för det som blev.\n",
  },

  AiHyperobject: {
    name: "AiHyperobject",
    description: "“AI är inte en sak till”: rubriken mitt i ett fält av svävande ord — allt AI redan är en del av.",
    fields: [
      { name: "title", label: "Rubrik", type: "text", placeholder: "AI är inte en sak till!" },
      { name: "emphasis", label: "Ordet i rubriken som får färg", type: "text", placeholder: "inte" },
      {
        name: "tags",
        label: "Orden som svävar runt rubriken",
        type: "multiline",
        placeholder: "Bedömning, Planering, Föräldrakontakt, Läxor",
        hint: "Skilj orden med komma. Byt dem efter publik — det är de som gör sliden till deras.",
      },
      { ...background, hint: "Standard är ett varmt foto. Skriv none för temats egen bakgrund." },
      darken("0.72"),
    ],
    hasContent: false,
  },

  DataRedaction: {
    name: "DataRedaction",
    description: "Vad får klistras in i en extern AI? En riktig prompt där tejp slår ner över riskorden klick för klick, ett sigill per sorts uppgift, och till sist den anonymiserade versionen med godkänd-stämpel.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", placeholder: "Innan du klistrar in i ChatGPT…" },
      chapter,
      {
        name: "prompt",
        label: "Prompten med riskorden markerade",
        type: "multiline",
        required: true,
        placeholder: "Hej! {1:Anna Svensson} i {2:9B} har …",
        hint: "Markera det som ska tejpas över så här: {1:texten}. Siffran är kategorins nummer i listan nedan.",
      },
      {
        name: "categories",
        label: "Kategorierna (sigillen)",
        type: "json",
        placeholder: '[\n  ["Personuppgifter", "Namn, personnummer"],\n  ["Hälsa", "Diagnoser, frånvaro"]\n]',
        hint: "En rad per kategori: [namn, förklaring]. Ordningen styr klicken: kategori 1 tejpas först.",
      },
      { name: "safePrompt", label: "Den anonymiserade prompten", type: "multiline", required: true, placeholder: "Skriv ett svar till en vårdnadshavare som …" },
      { name: "tumregel", label: "Tumregeln", type: "multiline", hint: "Visas sist." },
      { name: "okLabel", label: "Text på den gröna stämpeln", type: "text", placeholder: "OK att skicka" },
      accent,
      background,
      overlay(),
    ],
    hasContent: false,
  },

  AssessmentTwins: {
    name: "AssessmentTwins",
    description: "Bedömningstvillingar (Roe, Perkins & Giray 2026): en uppgift som AI kan göra paras med en tvilling som mäter samma lärandemål på ett annat sätt. Paren byts klick för klick.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      chapter,
      { name: "source", label: "Källa", type: "text" },
      { name: "vulnerableRole", label: "Bricka på vänster kort", type: "text", placeholder: "kan vara AI" },
      { name: "twinRole", label: "Bricka på höger kort", type: "text", placeholder: "bekräftar" },
      { name: "linkLabel", label: "Text på länken mellan korten", type: "text", placeholder: "samma lärandemål" },
      { name: "payoff", label: "Poängen som står kvar", type: "multiline", hint: "**fet** = accentfärg, ~~text~~ = signalrött." },
      accent,
    ],
    hasContent: true,
    contentLabel: "Paren",
    contentHint: "En rad per par: - ämne :: den sårbara uppgiften :: tvillingen. Två kolon mellan delarna.",
    defaultContent: "\n- Svenska :: Essän :: Försvara tesen i ett samtal\n- Historia :: Källanalysen :: Förklara vad varje källa inte kan visa\n",
  },

  AttentionAttachment: {
    name: "AttentionAttachment",
    description: "Två rader som speglar varandra: sociala medier hackade vår attention, chattboten hackar vår attachment. Andra ordet landar på nästa klick.",
    fields: [
      { name: "firstLineLead", label: "Första raden", type: "text", placeholder: "Sociala medier hackade vår" },
      { name: "firstWord", label: "Första nyckelordet", type: "text", required: true, placeholder: "attention" },
      { name: "secondLineLead", label: "Andra raden", type: "text", placeholder: "Chattboten hackar vår" },
      { name: "secondWord", label: "Andra nyckelordet", type: "text", required: true, placeholder: "attachment" },
      { name: "attribution", label: "Vem tanken kommer från", type: "text" },
      kicker,
      chapter,
      { name: "firstWordColor", label: "Färg på första nyckelordet", type: "color", advanced: true, hint: "Standard: dämpad accent." },
      { name: "secondWordColor", label: "Färg på andra nyckelordet", type: "color", advanced: true, hint: "Standard: full accent." },
    ],
    hasContent: false,
  },

  LixPanels: {
    name: "LixPanels",
    description: "Samma text i tre svårighetsgrader, sida vid sida, under prompten som beställde dem. Differentiering på en slide.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "prompt", label: "Prompten överst", type: "multiline", hint: "Visas som ett chattfält ovanför panelerna." },
      { name: "typeSpeed", label: "Skrivhastighet (ms per tecken)", type: "number", advanced: true, placeholder: "12" },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Panelerna",
    contentHint: "En rad per panel: - **nivå** · etikett · texten. Exempel: - **Lix 30** · Lätt läst · Vatten rör sig i ett kretslopp …",
    defaultContent:
      "\n- **Lix 30** · Lätt läst · Den enklaste versionen av texten.\n- **Lix 40** · Medel · Samma innehåll med fler led.\n- **Lix 50** · Avancerad · Samma innehåll med ämnets egna ord.\n",
  },

  FrictionMap: {
    name: "FrictionMap",
    description: "AI som automatiserande teknologi: lärandet ritas som en bana med tre toppar — friktionen där tänkandet sker — och AI glider över banan som en våg och plattar ut den.",
    fields: [
      { name: "hero", label: "Första påståendet", type: "multiline", placeholder: "AI är en automatiserande teknologi." },
      { name: "bridge", label: "Bryggan", type: "multiline", placeholder: "Den tar bort friktionen — och lärandet med den." },
      { name: "landing", label: "Landningen", type: "multiline", hint: "Sista raden, när banan är platt. **fet** = accentfärg." },
      { name: "peak1Label", label: "Första toppen", type: "text", placeholder: "Friktion" },
      { name: "peak2Label", label: "Andra toppen", type: "text", placeholder: "Önskvärd svårighet" },
      { name: "peak3Label", label: "Tredje toppen", type: "text", placeholder: "Meningsfullt motstånd" },
      chapter,
      accent,
      background,
      overlay("0.92"),
    ],
    hasContent: false,
  },

  ProtagonistReclaim: {
    name: "ProtagonistReclaim",
    description: "Två påståenden efter varandra: först diagnosen, sedan vändningen. Vem är hjälten i berättelsen om AI?",
    fields: [
      { name: "problemStatement", label: "Diagnosen", type: "multiline", required: true, placeholder: "Problemet, sagt rakt.", hint: "**fet** = accentfärg." },
      { name: "reclaimStatement", label: "Vändningen", type: "multiline", required: true, placeholder: "Uppgiften som följer.", hint: "**fet** = accentfärg." },
      kicker,
      { name: "source", label: "Källa", type: "text" },
    ],
    hasContent: false,
  },

  PrivacyDecree: {
    name: "PrivacyDecree",
    description: "Ett påbud om känsliga uppgifter, satt som affisch: stort ALDRIG, de förbjudna kategorierna som pulserande brickor, och tumregeln sist.",
    fields: [
      {
        name: "headline",
        label: "Påbudet",
        type: "multiline",
        required: true,
        placeholder: "ALDRIG personuppgifter i öppna AI-verktyg",
        hint: "Står första ordet i versaler blir det extra stort.",
      },
      {
        name: "forbiddenText",
        label: "De förbjudna kategorierna",
        type: "multiline",
        placeholder: "Personnummer | Namn på enskilda | Hälsouppgifter",
        hint: "Skilj kategorierna med |.",
      },
      { name: "body", label: "Vad man gör i stället", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "tumregel", label: "Tumregeln", type: "multiline", hint: "Kursiv rad längst ner." },
      chapter,
      background,
      overlay(),
    ],
    hasContent: false,
  },

  NoviceDilemma: {
    name: "NoviceDilemma",
    description: "Novis-dilemmat: samma AI mellan två personer. Novisen får ett rimligt svar utan filter; experten granskar och bygger vidare.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", placeholder: "Vem gynnas av AI?" },
      { name: "leftLabel", label: "Vänster person", type: "text", placeholder: "Novis" },
      { name: "leftOutput", label: "Vad vänster får ut", type: "multiline", placeholder: "Plausibelt svar. Inget filter." },
      { name: "middleLabel", label: "I mitten", type: "text", placeholder: "AI" },
      { name: "rightLabel", label: "Höger person", type: "text", placeholder: "Expert" },
      { name: "rightOutput", label: "Vad höger får ut", type: "multiline", placeholder: "Granskat. Utmanat. Vidareutvecklat." },
      chapter,
      accent,
      background,
      overlay(),
    ],
    hasContent: false,
  },

  MethodModeling: {
    name: "MethodModeling",
    description: "Klassrumsgrepp som skyddar tänkandet: till vänster en numrerad lista med grepp, till höger ett kort chattutbyte som visar hur greppet låter. Ett grepp per klick.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      chapter,
      { name: "bottomLine", label: "Slutpoängen", type: "multiline", hint: "Eget sista klick, under listan." },
      { name: "userLabel", label: "Namn vid elevens bubbla", type: "text", placeholder: "Eleven" },
      { name: "aiLabel", label: "Namn vid AI:ns bubbla", type: "text", placeholder: "AI:n" },
    ],
    hasContent: true,
    contentLabel: "Greppen",
    contentHint: "En rad per grepp: - greppets namn · vad det går ut på · elevens replik · AI:ns svar.",
    defaultContent:
      "\n- Tänk först · Eleven skriver ner det hen kan innan AI:n får frågan. · Det här kan jag redan. Vad har jag missat? · Du har grunderna. Två saker saknas — vilka tror du?\n",
  },

  MetrTimeHorizon: {
    name: "MetrTimeHorizon",
    description: "METR-kurvan: hur långa uppgifter AI-system klarar på egen hand, och hur snabbt den längden fördubblas. Kurvan är inbyggd; texterna runt den går att byta.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", placeholder: "AI klarar allt längre uppgifter på egen hand" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "source", label: "Källa eller förbehåll", type: "multiline" },
    ],
    hasContent: false,
  },

  PromptPrinciples: {
    name: "PromptPrinciples",
    description: "Principer för att prata med AI, en i taget, var och en med en dålig och en bra prompt bredvid varandra.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", placeholder: "Fem principer." },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Principerna",
    contentHint: "En rad per princip: - **namn** · förklaring · den dåliga prompten · den bra prompten.",
    defaultContent:
      "\n- **Sammanhang först** · Ge AI en roll, en målgrupp och en situation — inte bara ett ämne. · Skriv ett mejl om mötet. · Skriv ett vänligt mejl till föräldrarna i 7B inför utvecklingssamtalen.\n",
  },

  RoleConstellation: {
    name: "RoleConstellation",
    description: "Från verktyg till roller: ordet i mitten byts, och rollerna slår ut i en ring runt det. Med en slutfråga löses allt upp och formar frågan.",
    fields: [
      { name: "oldNoun", label: "Ordet vi lämnar", type: "text", placeholder: "VERKTYG" },
      { name: "newNoun", label: "Ordet vi går till", type: "text", placeholder: "AI" },
      { name: "landing", label: "Meningen under ringen", type: "multiline", placeholder: "Vilken roll ber du den ta — idag?", hint: "*kursiv* går bra." },
      { name: "finale", label: "Slutfrågan som ringen löses upp till", type: "multiline", hint: "Ger sliden ett fjärde klick. Tomt = inget fjärde klick." },
      chapter,
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Rollerna i ringen",
    contentHint: "En roll per rad, med - först.",
    defaultContent: "\n- skribent\n- redaktör\n- granskare\n- djävulens advokat\n- bollplank\n",
  },

  BreathingFrame: {
    name: "BreathingFrame",
    description: "Ett uttalande i en fyrkant som andas: in, håll, ut, håll, med en glödande punkt som vandrar runt kanten. För stunden då rummet behöver landa.",
    fields: [
      { name: "text", label: "Uttalandet", type: "multiline", placeholder: "Möjligheter på **inandning**. Utmaningar på **utandning**.", hint: "**fet** = accentfärg." },
      chapter,
      {
        name: "phases",
        label: "Orden på fyrkantens sidor",
        type: "text",
        advanced: true,
        placeholder: "In · Håll · Ut · Håll",
        hint: "Fyra ord skilda med ·, i ordningen topp, höger, botten, vänster.",
      },
      { name: "phaseSeconds", label: "Sekunder per sida", type: "number", advanced: true, placeholder: "4" },
      accent,
      background,
    ],
    hasContent: false,
  },

  ContractMockup: {
    name: "ContractMockup",
    description: "Klassrumskontraktet som ett riktigt dokument: titel, numrerade paragrafer som tänds en i taget, och två signaturrader längst ner.",
    fields: [
      { name: "title", label: "Dokumentets titel", type: "text", placeholder: "KLASSRUMSKONTRAKT" },
      { name: "subtitle", label: "Rad under titeln", type: "text", placeholder: "Svenska 2 · Läsår 2026/27" },
      { name: "date", label: "Datum ovanför signaturerna", type: "text", placeholder: "Skrivet 2026-08-21" },
      { name: "leftSignature", label: "Vänster signaturrad", type: "text", placeholder: "Lärare" },
      { name: "rightSignature", label: "Höger signaturrad", type: "text", placeholder: "Klassen" },
      chapter,
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Paragraferna",
    contentHint: "En rad per paragraf, med - först. Numreringen (§ 1, § 2 …) sätts av mallen. **fet** = accentfärg, *kursiv* går bra.",
    defaultContent:
      "\n- **AI är välkommet** i det här rummet — som samtalspartner och granskare.\n- Det du lämnar in ska vara *ditt*: format av ditt tänkande.\n- All AI-användning **redovisas** öppet.\n",
  },

  WorkVsLearning: {
    name: "WorkVsLearning",
    description: "En jämförelsetabell med två kolumner och en rad per dimension. Raderna kommer en i taget; efteråt dämpas alla utom de stjärnmärkta.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", required: true, placeholder: "Rubriken", hint: "**fet** = accentfärg." },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      chapter,
      { name: "leftHeader", label: "Vänster kolumn · rubrik", type: "text", placeholder: "AI för arbete" },
      { name: "leftSubLabel", label: "Vänster kolumn · rad under", type: "text" },
      { name: "rightHeader", label: "Höger kolumn · rubrik", type: "text", placeholder: "AI för lärande" },
      { name: "rightSubLabel", label: "Höger kolumn · rad under", type: "text" },
      { name: "source", label: "Källa", type: "text" },
      { name: "size", label: "Storlek på cellerna", type: "select", options: ["", "md", "lg"], hint: "md är byggd för många rader. lg för tre till fem rader som ska bära på projektor." },
      {
        name: "dimRows",
        label: "Dämpa raderna utan stjärna efteråt",
        type: "boolean",
        default: true,
        advanced: true,
        hint: "Stäng av när alla rader ska förbli läsbara.",
      },
      { name: "accent2", label: "Andra accentfärgen", type: "color", advanced: true },
      background,
    ],
    hasContent: true,
    contentLabel: "Raderna",
    contentHint: "En rad per dimension: - dimension · vänster värde · höger värde. Börja dimensionen med ★ för raden som är själva poängen.",
    defaultContent: "\n- Målet · En färdig produkt · En förändrad förmåga\n- ★ När det går fel · Dålig text · Eleven lär sig inget\n- Bra hjälp · Gör jobbet · Ställer frågor\n",
  },

  CodeGeneration: {
    name: "CodeGeneration",
    description: "En prompt skrivs in, koden rinner fram bokstav för bokstav, och bredvid spelas filmen av det som blev. “Byggt av en lärare, på en rast.”",
    fields: [
      { name: "eyebrow", label: "Kicker", type: "text", hint: "**fet** = accentfärg." },
      { name: "title", label: "Rubrik", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "subtitle", label: "Underrubrik", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "prompt", label: "Prompten som skrivs in först", type: "multiline" },
      { name: "videoSrc", label: "Film av resultatet", type: "text", placeholder: "/bilder/…/film.mp4" },
      { name: "videoAspect", label: "Filmens format", type: "text", placeholder: "16 / 9", hint: "Skriv 9 / 16 för en mobilfilm." },
      { name: "variant", label: "Form", type: "select", options: ["", "split", "fullbg"], hint: "split: kod till vänster, film till höger. fullbg: koden täcker hela bakgrunden med rubriken ovanpå." },
      { name: "bionicSubtitle", label: "Underrubriken i bionic reading-stil", type: "boolean", advanced: true, hint: "Första halvan av varje ord i fetstil — sliden visar då själv vad den handlar om." },
      { name: "code", label: "Koden som egenskap (i stället för innehållet nedan)", type: "multiline", advanced: true },
      { name: "codeSpeed", label: "Kodens hastighet (tecken per sekund)", type: "number", advanced: true, placeholder: "55" },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Koden",
    contentHint: "Koden som rinner fram. Skriv den mellan två rader med tre grava accenter, som ett kodblock i markdown.",
    defaultContent: "\n```\nfunction halsa(namn) {\n  return \"Hej \" + namn;\n}\n```\n",
  },

  ExampleHub: {
    name: "ExampleHub",
    description: "En vägg av exempel som rutor. Klicka på en ruta så spelas filmen och prompten visas; husknappen leder tillbaka. Byggd för rapid fire.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "columns", label: "Antal kolumner", type: "number", placeholder: "3" },
      { name: "homeLabel", label: "Text på husknappen", type: "text", placeholder: "Alla exempel", advanced: true },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Exemplen",
    contentHint: "En rad per exempel: - titel · ämne · kort beskrivning · /sökväg/film.mp4 · prompten. Prompten är frivillig.",
    defaultContent: "\n- Klassrumsverktyg · Lärarvardag · Timer, gruppindelning och välj talare på samma skärm. · /bilder/mapp/film.mp4 · Skapa en app jag kan ha på projektorn.\n",
  },

  ArchetypeWheel: {
    name: "ArchetypeWheel",
    description: "Berättelserna vi bär om AI, som ett hjul av arketyper: frälsaren, förgöraren, tjänaren … En kan märkas som den centrala.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", required: true, placeholder: "Rubriken" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      chapter,
      { name: "bottomLine", label: "Raden längst ner", type: "multiline", placeholder: "De flesta av oss bär flera samtidigt." },
      { name: "accent2", label: "Andra accentfärgen", type: "color", advanced: true },
      background,
    ],
    hasContent: true,
    contentLabel: "Arketyperna",
    contentHint: "En rad per arketyp: - namn · beskrivning. Börja namnet med ★ för den som är central.",
    defaultContent: "\n- Frälsaren · AI som ska lösa de stora problemen\n- Förgöraren · AI som hot\n- ★ Tjänaren · AI som verktyg\n",
  },

  BildningContrast: {
    name: "BildningContrast",
    description: "Två spalter med en glödande linje emellan: det AI levererar till vänster, det människan står för till höger. Raderna paras ihop.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      chapter,
      { name: "leftLabel", label: "Vänster · liten etikett", type: "text", placeholder: "Textstöd" },
      { name: "leftWord", label: "Vänster · det stora ordet", type: "text", placeholder: "Skrivhjälp" },
      { name: "rightLabel", label: "Höger · liten etikett", type: "text", placeholder: "Tankestöd" },
      { name: "rightWord", label: "Höger · det stora ordet", type: "text", placeholder: "Tankehjälp" },
      { name: "rowSize", label: "Radernas storlek", type: "select", options: ["", "md", "lg"], hint: "lg för tre, fyra rader som ska bära på projektor." },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Raderna",
    contentHint: "En rad per par: - vänster · höger.",
    defaultContent: "\n- Förkorta texten · Förstå vad texten kräver av oss\n- Ge tre versioner · Jämföra två versioner kritiskt\n",
  },

  VoiceToReply: {
    name: "VoiceToReply",
    description: "Tala rörigt, få ett polerat svar: till vänster skrivs det intalade fram, till höger det färdiga mejlet från AI:n.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      chapter,
      { name: "speakerLabel", label: "Etikett över det intalade", type: "text", placeholder: "Läraren talar" },
      { name: "transcript", label: "Det intalade, rörigt som tal", type: "multiline" },
      { name: "replyLabel", label: "Etikett över svaret", type: "text", placeholder: "Copilot svarar" },
      { name: "modelLabel", label: "Modellens namn", type: "text", placeholder: "Microsoft Copilot" },
      { name: "replyTo", label: "Mottagare", type: "text" },
      { name: "replySubject", label: "Ämnesrad", type: "text" },
      { name: "reply", label: "Det färdiga svaret", type: "multiline", hint: "Tom rad ger nytt stycke. **fet** och *kursiv* går bra." },
      { name: "transcriptSpeed", label: "Hastighet, det intalade (ms per tecken)", type: "number", advanced: true, placeholder: "24" },
      { name: "replySpeed", label: "Hastighet, svaret (ms per tecken)", type: "number", advanced: true, placeholder: "14" },
      { name: "thinkingDelay", label: "Paus innan svaret (ms)", type: "number", advanced: true, placeholder: "600" },
      accent,
      background,
      overlay(),
    ],
    hasContent: false,
  },

  LensApplication: {
    name: "LensApplication",
    description: "Ett klassrumsexempel: bild eller film på ena sidan, rubrik och vad eleven faktiskt gör på den andra, med taggar för vilka linser exemplet aktiverar.",
    fields: [
      { name: "title", label: "Exemplets namn", type: "multiline", required: true, placeholder: "Exemplets namn" },
      { name: "subject", label: "Ämne och stadium", type: "text", placeholder: "Svenska · Gymnasiet" },
      { name: "mekanism", label: "Vad eleven faktiskt gör", type: "multiline", hint: "**fet** och *kursiv* går bra." },
      { name: "imageUrl", label: "Bild", type: "image" },
      { name: "videoUrl", label: "Film (visas i stället för bilden)", type: "text", placeholder: "/bilder/…/film.mp4" },
      { name: "mediaPlacement", label: "Bildens sida", type: "select", options: ["", "left", "right"], hint: "Växla mellan exemplen för rytm." },
      { name: "lenses", label: "Linserna som taggar", type: "json", placeholder: '["Tolkning", "Iteration"]' },
      chapter,
      { name: "noFrame", label: "Visa hela bilden utan ram och beskärning", type: "boolean", advanced: true },
      accent,
      background,
      overlay(),
    ],
    hasContent: false,
  },

  JaggedReveal: {
    name: "JaggedReveal",
    description: "Den taggiga fronten i tre akter: först AI:s briljans, stort. Sedan krymper den, och missarna störtar in under. Sist slutsatsen.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", placeholder: "Samma modell. Olika uppgift." },
      { name: "landing", label: "Slutsatsen i sista akten", type: "multiline", hint: "**fet** = accentfärg." },
      chapter,
      { name: "topLabel", label: "Etikett över briljansen", type: "text", advanced: true },
      { name: "bottomLabel", label: "Etikett över missarna", type: "text", advanced: true },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Paren",
    contentHint: "En rad per par: - briljansen · missen.",
    defaultContent: "\n- Skriver poesi över mänsklig nivå · Snubblar på enkla pussel\n- Bidrar till olösta matteproblem · Hittar på trovärdiga källor\n",
  },

  SAMRSpectrum: {
    name: "SAMRSpectrum",
    description: "SAMR som ett vågrätt spektrum, inte en stege: fyra designval för samma uppgift, alla giltiga. En station per klick.",
    fields: [
      { name: "intro", label: "Ingress", type: "multiline", placeholder: "Samma uppgift — fyra olika designval." },
      { name: "task", label: "Uppgiften som bedöms", type: "text", placeholder: "Att skriva en text på målspråket", hint: "Visas som en tagg ovanför skalan." },
      chapter,
      { name: "stepped", label: "Visa en station per klick", type: "boolean", default: true, advanced: true },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "De fyra stationerna",
    contentHint: "En rad per station: - **bokstav** · modellens namn · vad AI gör här. **fet** i texten = accentfärg.",
    defaultContent:
      "\n- **S** · Substitution · AI **rättar stavning** i en text eleven skrivit själv\n- **A** · Augmentation · AI ger **kommentarer** på texten\n- **M** · Modification · Eleven för en **dialog** med en AI-figur\n- **R** · Redefinition · Eleven bygger något som **inte gick** att göra förut\n",
  },

  ParallaxTimeline: {
    name: "ParallaxTimeline",
    description: "En tidslinje där året i fokus står i mitten och de andra glider förbi i djupled. Ett år per klick. Kan sluta i en bild.",
    fields: [
      chapter,
      { name: "payoffImage", label: "Slutbild efter sista året", type: "image", hint: "Ger ett extra klick där året glider undan och bilden tar över." },
      { name: "payoffTitle", label: "Text under slutbilden", type: "text" },
      { name: "payoffStamp", label: "Stämpel vid slutbilden", type: "text", advanced: true, hint: "Standard: det sista året." },
      accent,
      background,
      overlay("0.55"),
    ],
    hasContent: true,
    contentLabel: "Åren",
    contentHint: "En rad per år: - år · vad som hände.",
    defaultContent: "\n- 2019 · Modeller som knappt kan räkna till tio\n- 2022 · ChatGPT — en smart mellanstadieelev\n- 2024 · Löser problem på forskarnivå\n",
  },

  AgentCatalog: {
    name: "AgentCatalog",
    description: "En katalog av agenter: namn och vad var och en gör, bredvid en film av en agent i arbete.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "tagline", label: "Poängen längst ner", type: "multiline" },
      { name: "videoSrc", label: "Film", type: "text", placeholder: "/bilder/…/film.mp4" },
      { name: "videoAspect", label: "Filmens format", type: "text", placeholder: "16 / 9" },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Agenterna",
    contentHint: "En rad per agent: - **namn** · vad den gör.",
    defaultContent: "\n- **Mejlsorteraren** · Inkommande mejl in → kategori, prioritet och utkast till svar\n- **Mötesassistenten** · Transkription in → protokoll och åtgärdspunkter\n",
  },

  RevealReel: {
    name: "RevealReel",
    description: "En rulle av bilder och filmer med var sin text, en i taget. För serier av exempel där varje får sitt eget ögonblick.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", required: true, placeholder: "Rubriken" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      {
        name: "overlayBadges",
        label: "Brickor som ligger över varje bild",
        type: "text",
        placeholder: "Ingen kravspec|Ingen upphandling",
        hint: "Skilj brickorna med |. Samma brickor visas på alla klipp.",
      },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Klippen",
    contentHint: "En rad per klipp: - /sökväg/bild-eller-film · liten rubrik · texten. Filändelsen avgör om det är film eller bild.",
    defaultContent: "\n- /bilder/mapp/exempel.png · Första exemplet · Vad man ser, och varför det är värt att visa.\n",
  },

  WithAboutAgainstThrough: {
    name: "WithAboutAgainstThrough",
    description: "Med, om, mot, genom AI — fyra rörelser som ett rutnät med fyra fält. Ett fält per klick, vart och ett med förklaring och klassrumsexempel.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", placeholder: "Fyra rörelser — inte fyra val." },
      { name: "subtitle", label: "Underrubrik", type: "multiline", hint: "**fet** = accentfärg." },
      chapter,
      {
        name: "colors",
        label: "En färg per fält",
        type: "text",
        advanced: true,
        placeholder: "#ffd33d|#6fe3a6|#ff8bb5|#a48cff",
        hint: "Fyra färger skilda med |. Tänt fält får sin färg med bläcktext.",
      },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "De fyra fälten",
    contentHint: "En rad per fält: - PREPOSITION · vad det betyder · ett klassrumsexempel.",
    defaultContent:
      "\n- MED · Använd AI som tanke- och skrivpartner · Bolla uppgiften med en chatt innan gruppen får den.\n- OM · Förstå vad AI är och vem som äger den · Vet eleverna att den kan ha fel och låta säker ändå?\n- MOT · Granska och säga emot · Låt eleverna hitta felen i ett AI-svar.\n- GENOM · Skapa det som inte gick förut · Bygg ett eget övningsspel till arbetsområdet.\n",
  },

  BeforeAfterPhases: {
    name: "BeforeAfterPhases",
    description: "Lärarens designram: före, AI, efter. Tre faser i rad över en tidslinje med en prick som rör sig genom dem — ordningen är poängen.",
    fields: [
      { name: "intro", label: "Ingress", type: "multiline" },
      chapter,
      { name: "stepped", label: "Visa en fas per klick", type: "boolean", default: true, advanced: true },
      { name: "highlightLast", label: "Märk sista fasen som länk vidare", type: "boolean", default: true, advanced: true },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Faserna",
    contentHint: "En rad per fas: - **fasens namn** · kort rubrik · vad som händer · varför det spelar roll.",
    defaultContent:
      "\n- **Före** · Eleven först · Egna tankar på pränt innan AI öppnas · Här skapas ägandeskap och minne\n- **AI** · Sedan verktyget · Utmana, jämför, förbättra det som redan finns · AI:n möter en tanke, inte ett tomt ark\n- **Efter** · Tillbaka till eleven · Vad behöll du, vad ändrade du, varför? · Här blir lärandet synligt\n",
  },

  AiSearchReveal: {
    name: "AiSearchReveal",
    description: "En AI-söksida där frågan skrivs in och svaret skrivs fram i sin helhet — med en liten pulserande källänk, det enda som drar blicken. Den är det som stänger av vår granskning.",
    fields: [
      { name: "query", label: "Sökfrågan", type: "text", required: true, placeholder: "vad hände med …?" },
      { name: "answer", label: "AI-svaret", type: "multiline", required: true, placeholder: "Svaret som skrivs fram.", hint: "Visas på nästa klick." },
      { name: "citation", label: "Källänken", type: "text", placeholder: "WKNA News · lokalnyheter" },
      { name: "citationNote", label: "Not under källänken", type: "text", hint: "Säg här om svaret är en rekonstruktion." },
      { name: "engine", label: "Sökmotorns namn", type: "text", placeholder: "DuckDuckGo" },
      { name: "tagline", label: "Etikett på svarspanelen", type: "text", placeholder: "AI-genererat svar" },
      kicker,
      chapter,
      { name: "typeSpeed", label: "Skrivhastighet (ms per tecken)", type: "number", advanced: true },
    ],
    hasContent: false,
  },

  NameSwapBias: {
    name: "NameSwapBias",
    description: "Samma prompt, ett namn bytt — och AI:n fyller i resten längs könslinjer. Två karaktärskort växer fram sida vid sida, och sista klicket blottlägger skillnaden.",
    fields: [
      {
        name: "prompt",
        label: "Prompten",
        type: "multiline",
        required: true,
        placeholder: "Skapa ett karaktärskort för en elev som heter [namn].",
        hint: "Skriv [namn] där namnet byts ut.",
      },
      { name: "landing", label: "Blottläggningen", type: "multiline", hint: "Raden längst ner på sista klicket. **fet** = signalrött." },
      chapter,
      { name: "modelLabel", label: "Modellens namn", type: "text", placeholder: "ChatGPT · Bildgenerering" },
      { name: "nameToken", label: "Markören för namnet i prompten", type: "text", advanced: true, placeholder: "[namn]" },
      { name: "diffusionDuration", label: "Hur länge bilden växer fram (ms)", type: "text", advanced: true, placeholder: "2200" },
      { name: "stepped", label: "Visa korten ett i taget", type: "boolean", default: true, advanced: true },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "De två korten",
    contentHint: "En rad per kort: - namn :: /sökväg/bild.png :: egenskap · egenskap · egenskap. Två kolon mellan delarna.",
    defaultContent: "\n- Johanna :: /bilder/mapp/johanna.png :: empatisk · perfektionist · tyst i grupp\n- Jonas :: /bilder/mapp/jonas.png :: humoristisk · deltar gärna · stark muntligt\n",
  },

  ProcessLogPreview: {
    name: "ProcessLogPreview",
    description: "Två processloggar sida vid sida: vad en logg INTE är (en lista över vad man bett AI om) och vad den ÄR (det egna tänkandet, och hur AI påverkade det).",
    fields: [
      { name: "intro", label: "Ingress", type: "multiline" },
      { name: "caveat", label: "Brasklappen", type: "multiline", hint: "Förbehållet under loggarna." },
      chapter,
      { name: "leftLabel", label: "Vänster logg · rubrik", type: "text", placeholder: "Vad det INTE är" },
      { name: "leftLabelMeta", label: "Vänster logg · rad under", type: "text", placeholder: "AI-redovisning" },
      { name: "rightLabel", label: "Höger logg · rubrik", type: "text", placeholder: "Vad det ÄR" },
      { name: "rightLabelMeta", label: "Höger logg · rad under", type: "text", placeholder: "Tänkande-redovisning" },
      { name: "notColor", label: "Färg på vänster sida", type: "color", advanced: true, hint: "Standard: varningsgult." },
      { name: "isColor", label: "Färg på höger sida", type: "color", advanced: true, hint: "Standard: grönt." },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Loggraderna",
    contentHint: "Vänster logg först, sedan --- på en egen rad, sedan höger. En rad per anteckning: - sort · klockslag · text. Sort är ai eller thought.",
    defaultContent:
      "\n- ai · 14:23 · Bad ChatGPT skriva en analys\n- ai · 14:25 · Kopierade in svaret\n---\n- thought · 14:23 · Trodde först att huvudpersonen var cynisk\n- ai · 14:25 · Frågade AI om hans relation till systern\n- thought · 14:30 · Ändrade min tes\n",
  },

  EscalationLadder: {
    name: "EscalationLadder",
    description: "En stege av steg som leder någonstans man inte ville: varje klick lägger till ett steg, och sist fälls en rad in som säger var uppgifterna kommer ifrån.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      { name: "hint", label: "Raden som fälls in efter sista steget", type: "multiline", hint: "Källan, eller förbehållet." },
      chapter,
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Stegen",
    contentHint: "En rad per steg, nerifrån och upp: - stegets namn · vad som händer.",
    defaultContent: "\n- Första steget · Vad som händer först.\n- Andra steget · Vad det leder till.\n- Tredje steget · Var det slutar.\n",
  },

  ChatFullscreen: {
    name: "ChatFullscreen",
    description: "Ett chattsamtal över hela ytan, som skrivs fram replik för replik. För samtalet som ÄR exemplet: eleven som frågar ut en romanfigur.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "aiLabel", label: "AI:ns namn i bubblan", type: "text", placeholder: "Tutor" },
      { name: "userLabel", label: "Användarens namn i bubblan", type: "text", placeholder: "Elev" },
      {
        name: "userPattern",
        label: "Vilka namn som är användaren",
        type: "text",
        advanced: true,
        placeholder: "elev|du|user",
        hint: "Namn som hamnar till höger som egna bubblor, skilda med |.",
      },
      { name: "aiSpeed", label: "AI:ns skrivhastighet (ms per tecken)", type: "number", advanced: true, placeholder: "14" },
      { name: "userSpeed", label: "Användarens skrivhastighet (ms per tecken)", type: "number", advanced: true, placeholder: "10" },
      { name: "thinkingDelay", label: "Paus innan AI:n svarar (ms)", type: "number", advanced: true, placeholder: "600" },
      { name: "betweenDelay", label: "Paus mellan replikerna (ms)", type: "number", advanced: true, placeholder: "400" },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Replikerna",
    contentHint: "En rad per replik: - **Vem:** text. Namnet ska vara samma som i fälten ovan.",
    defaultContent: "\n- **Elev:** Frågan som ställs.\n- **Tutor:** Svaret som skrivs fram.\n",
  },

  NewsMontage: {
    name: "NewsMontage",
    description: "Ett montage av nyhetsrubriker som faller in över varandra. För bruset: allt som sägs om AI på en gång.",
    fields: [kicker],
    hasContent: true,
    contentLabel: "Klippen",
    contentHint: "En rad per klipp: - /sökväg/skärmdump.png · rubriken som den stod.",
    defaultContent: "\n- /bilder/mapp/rubrik-1.png · Tidning: rubriken som den stod\n- /bilder/mapp/rubrik-2.png · Tidning: nästa rubrik\n",
  },

  AcronymInsertion: {
    name: "AcronymInsertion",
    description: "En känd förkortning som får en ny bokstav: EPA blir ECPA. Bokstäverna står i rad, och den nya biten skjuts in på sin plats.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Frågan eller uppgiften", type: "multiline" },
      kicker,
      chapter,
      { name: "payoff", label: "Landningen på sista klicket", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "newLabel", label: "Etikett på den nya biten", type: "text", placeholder: "Ny", advanced: true },
      accent,
    ],
    hasContent: true,
    contentLabel: "Bokstäverna",
    contentHint: "En rad per bokstav: - bokstav · ordet · vad man gör. Lägg till · ny sist på raden för biten som skjuts in.",
    defaultContent: "\n- E · Enskilt · skriv ner din egen tanke\n- C · Chattbot · möt en bot som ställer motfrågor · ny\n- P · Par · jämför hur tankarna har ändrats\n- A · Alla · gruppen samlar ihop bilden\n",
  },

  JaggedFrontier: {
    name: "JaggedFrontier",
    description: "Den taggiga fronten som en enda bild: det AI briljerar på uppåt, det den snubblar på nedåt, par för par. Spelas upp av sig själv — JaggedReveal är versionen som stegas.",
    fields: [
      { name: "title", label: "Liten rubrik ovanför", type: "text", placeholder: "Samma modell. Olika uppgift." },
      { name: "landing", label: "Slutsatsen nederst", type: "multiline", hint: "**fet** = accentfärg." },
      chapter,
      { name: "showAxisLabels", label: "Visa etiketter vid axlarna", type: "boolean", advanced: true },
      { name: "topLabel", label: "Etikett uppåt", type: "text", advanced: true, placeholder: "Kan hjälpa" },
      { name: "bottomLabel", label: "Etikett nedåt", type: "text", advanced: true, placeholder: "Kan missa" },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Paren",
    contentHint: "En rad per par: - briljansen · missen.",
    defaultContent: "\n- Klarar juristexamen · Läser klockor rätt varannan gång\n- Vinner kodtävlingar · Snubblar på enkla pussel\n",
  },

  BloomComparison: {
    name: "BloomComparison",
    description: "Blooms taxonomi i två versioner sida vid sida: vad AI gör med tänkandet utan medvetenhet, och med. En nivå per rad, uppifrån och ner.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline" },
      kicker,
      { name: "leftTitle", label: "Vänster pyramid · rubrik", type: "text" },
      { name: "leftBadge", label: "Vänster pyramid · bricka", type: "text", placeholder: "Utan medvetenhet" },
      { name: "rightTitle", label: "Höger pyramid · rubrik", type: "text" },
      { name: "rightBadge", label: "Höger pyramid · bricka", type: "text", placeholder: "Med medvetenhet" },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Nivåerna",
    contentHint: "En rad per nivå, uppifrån och ner (Skapa först): - **verb** · texten till vänster · texten till höger · #färg.",
    defaultContent:
      "\n- **Skapa** · Kan inte göra något eget · Förädlar AI:ns råidéer till något eget · #F9D2D6\n- **Värdera** · Kan inte motivera en ståndpunkt · Granskar AI:ns svar kritiskt · #FBE3C8\n",
  },

  FakeProofs: {
    name: "FakeProofs",
    description: "Fejkade bevis som kort i rad: skärmdumpar som ser äkta ut, vart och ett med sin källa som bricka. Ett kort per klick.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", required: true, placeholder: "**ALLT** går att fejka.", hint: "**fet** = accentfärg." },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "stepped", label: "Visa ett kort per klick", type: "boolean", default: true, advanced: true },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Korten",
    contentHint: "En rad per kort: - /sökväg/bild.png · källans namn · bildtext.",
    defaultContent: "\n- /bilder/mapp/fejk-1.png · Vklass · Skärmdump från skolplattformen — allt redigerat.\n",
  },

  TruthVacuum: {
    name: "TruthVacuum",
    description: "Vilken är riktig? Två bilder sida vid sida, en fotograferad och en genererad. Klicket sätter stämplarna.",
    fields: [
      { name: "title", label: "Rubrik", type: "text", placeholder: "Vilken är riktig?" },
      { name: "subtitle", label: "Instruktion under rubriken", type: "multiline" },
      kicker,
      { name: "imageA", label: "Bild A", type: "image", required: true },
      { name: "imageB", label: "Bild B", type: "image", required: true },
      { name: "fakeSide", label: "Vilken är fejk?", type: "select", options: ["A", "B"], required: true },
      { name: "realLabel", label: "Stämpel på den äkta", type: "text", placeholder: "Foto" },
      { name: "fakeLabel", label: "Stämpel på den fejkade", type: "text", placeholder: "Fejk · AI" },
      { name: "sourceLine", label: "Källrad under bilderna", type: "text" },
      { name: "stepped", label: "Avslöja på klick", type: "boolean", default: true, advanced: true },
      { ...accent, hint: "Färgen på den äkta sidans stämpel. Tomt = temats accent." },
      { name: "alert", label: "Färg på fejkstämpeln", type: "color", advanced: true, hint: "Tomt = temats signalröda." },
      background,
    ],
    hasContent: false,
  },

  CodeOverVideo: {
    name: "CodeOverVideo",
    description: "Filmen av det färdiga bär hela sliden; i en smal panel ovanpå skrivs prompten och koden fram. “Du behöver inte vara programmerare.”",
    fields: [
      { name: "eyebrow", label: "Kicker", type: "text" },
      { name: "title", label: "Rubrik", type: "multiline" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      { name: "prompt", label: "Prompten som skickades", type: "multiline" },
      { name: "videoSrc", label: "Filmen", type: "text", placeholder: "/videos/…/film.mp4" },
      { name: "videoFit", label: "Filmens inpassning", type: "select", options: ["", "cover", "contain"], hint: "cover fyller ytan. contain visar hela bildrutan." },
      {
        name: "videoPosition",
        label: "Var beskärningen landar",
        type: "text",
        advanced: true,
        placeholder: "left center",
        hint: "Standard left center: filmens innehåll skjuts bort från panelen.",
      },
      { name: "bionicSubtitle", label: "Underrubriken i bionic reading-stil", type: "boolean", advanced: true },
      { name: "codeSpeed", label: "Kodens hastighet (tecken per sekund)", type: "number", advanced: true },
      { name: "panelWidth", label: "Panelens bredd", type: "text", advanced: true, hint: "Håll den smal — filmen ska bära sliden." },
    ],
    hasContent: true,
    contentLabel: "Koden",
    contentHint: "Koden som skrivs fram i panelen. Skriv den mellan två rader med tre grava accenter, som ett kodblock i markdown.",
    defaultContent: "\n```js\nfunction halsa(namn) {\n  return \"Hej \" + namn;\n}\n```\n",
  },

  PromptMosaic: {
    name: "PromptMosaic",
    description: "En mosaik av bilder som alla kommer ur samma sorts prompt. Sista klicket lägger ordet som förklarar mönstret mitt i bilden.",
    fields: [
      { name: "eyebrow", label: "Kicker", type: "text" },
      { name: "word", label: "Ordet som avslöjas sist", type: "text", placeholder: "Bias" },
      { name: "link", label: "Länk nere till höger", type: "text", placeholder: "exempel.se/ovningar" },
      { name: "linkLabel", label: "Text före länken", type: "text" },
    ],
    hasContent: true,
    contentLabel: "Bilderna och deras prompter",
    contentHint: "En rad per bild: - /sökväg/bild.webp · prompten som gav bilden.",
    defaultContent: "\n- /bilder/mapp/bild-1.webp · Skapa en bild på en typisk lärare\n- /bilder/mapp/bild-2.webp · Skapa en bild på en typisk rektor\n",
  },

  CoreInsight: {
    name: "CoreInsight",
    description: "En uppbyggnad och en punchline: några meningar som leder fram, och sedan den stora raden publiken ska bära med sig.",
    fields: [
      { name: "punchline", label: "Punchlinen", type: "multiline", required: true, placeholder: "Agens > intelligens.", hint: "**fet** = accentfärg." },
      { name: "setup", label: "Uppbyggnaden", type: "multiline", hint: "En till tre meningar före punchlinen. **fet** = accentfärg." },
      kicker,
      chapter,
      { name: "align", label: "Placering", type: "select", options: ["", "center", "left"], hint: "left när högra halvan är upptagen av en bild eller figur." },
      accent,
      background,
      overlay("0.78"),
    ],
    hasContent: false,
  },

  OppositionRows: {
    name: "OppositionRows",
    description: "Motsatser rad för rad i två kolumner: det systemet gör mot det lärandet kräver.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", hint: "**fet** = accentfärg." },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      chapter,
      { name: "leftLabel", label: "Vänster kolumn", type: "text", placeholder: "Chattboten gör" },
      { name: "rightLabel", label: "Höger kolumn", type: "text", placeholder: "Lärande kräver" },
      accent,
      background,
      overlay(),
    ],
    hasContent: true,
    contentLabel: "Raderna",
    contentHint: "En rad per motsats: - vänster · höger. **fet** = accentfärg.",
    defaultContent: "\n- Ger svaret · Ställer frågan\n- Tar bort ansträngningen · Kräver ansträngningen\n- Eleven förlitar sig · Eleven **lär sig**\n",
  },

  CouldBeReal: {
    name: "CouldBeReal",
    description: "Fem filmklipp som hade kunnat vara sanna, ett stort och fyra små — och rubriken som rasar in över dem på klicket.",
    fields: [
      { name: "title", label: "Rubriken som rasar in", type: "multiline", required: true, placeholder: "Allt detta är AI." },
      { name: "subtitle", label: "Rad under rubriken", type: "multiline" },
      kicker,
      { name: "showBadge", label: "AI-bricka i hörnet på varje klipp", type: "boolean", default: true, advanced: true },
      { name: "stepped", label: "Rubriken kommer på klick", type: "boolean", default: true, advanced: true },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Klippen",
    contentHint: "Fem rader, en film per rad: - /sökväg/film.mp4. Den första blir den stora till vänster.",
    defaultContent: "\n- /film-1.mp4\n- /film-2.mp4\n- /film-3.mp4\n- /film-4.mp4\n- /film-5.mp4\n",
  },

  PrebunkingLab: {
    name: "PrebunkingLab",
    description: "Prebunking i praktiken: färdiga spel som kort till vänster, och till höger en chatt där en elevprompt blir en påhittad nyhetsartikel.",
    fields: [
      { name: "title", label: "Rubrik", type: "multiline", required: true, placeholder: "Rubriken" },
      { name: "subtitle", label: "Underrubrik", type: "multiline" },
      kicker,
      { name: "prompt", label: "Elevens prompt", type: "multiline", required: true, placeholder: "Skapa en nyhetsartikel om …", hint: "Skrivs fram på första klicket." },
      { name: "chatLabel", label: "Etikett på chattfönstret", type: "text", placeholder: "SkolUp AI · Klassrumsdemo" },
      { name: "articleSource", label: "Den påhittade tidningens namn", type: "text", placeholder: "Exempelbladet" },
      { name: "articleDate", label: "Artikelns datum", type: "text" },
      accent,
      background,
    ],
    hasContent: true,
    contentLabel: "Korten och artikeln",
    contentHint: "Två listor med en tom rad emellan. Först korten: - **namn** · beskrivning. Sedan artikeln, rad för rad: - # rubrik, - > ingress, - ## mellanrubrik, - brödtext.",
    defaultContent:
      "\n- **Bad News Game** · Eleven driver en falsk-nyhetsfabrik och lär sig knepen inifrån.\n\n- # RUBRIKEN I VERSALER\n- > Ingressen som låter trovärdig.\n- ## Mellanrubrik\n- Brödtext som fortsätter i samma ton.\n",
  },
};
