"use client";
import { AnimatePresence, motion } from 'framer-motion';
import type { ReactNode } from 'react';
import { sceneEase } from '../shared/SceneMotion';
import s from './learning-choices.module.css';
type Props={step:number;still:boolean;v:(key:string)=>string;t:(key:string)=>ReactNode};
export function LearningChoices({step,still,v,t}:Props){
 const tr={duration:still?0:.85,ease:sceneEase};
 if(v('composition')==='ai-doping')return <><h1 className={s.dopingTitle}>{t('title')}</h1><p className={s.dopingSubtitle}>{t('subtitle')}</p><div className={s.dopingVial}><div className={s.vialCap} aria-hidden/><div className={s.vialBody}><motion.div className={s.vialLiquid} initial={false} animate={{height:[45,65,83][step]+'%'}} transition={tr}/><div className={s.vialLabel}>{t('vialLabel')}</div><i/><i/></div></div><div className={s.dopingCompare}><article><header>{t('productLabel')}</header><motion.div className={s.productText} initial={false} animate={{height:[40,65,90][step]}} transition={tr} aria-hidden>{Array.from({length:8},(_,i)=><i key={i} style={{width:[95,83,100,91,75,93,85,62][i]+'%'}}/>)}</motion.div><h2>{t(`phase${step+1}`)}</h2><p>{t(`detail${step+1}`)}</p></article><article><header>{t('abilityLabel')}</header><div className={s.ownAttempt} aria-hidden><i/><i/><b>?</b></div><p>{t('abilityQuestion')}</p></article></div><div className={s.dopingRail}>{[1,2,3].map(n=><span key={n} data-active={step===n-1}>0{n}<i/></span>)}</div></>;
 if(v('composition')==='two-voices')return <><div className={s.voicePhotos}>{[1,2].map(n=><motion.div key={n} initial={false} animate={{opacity:n===1?1:step?1:0}} transition={tr} style={{backgroundImage:`url("${v(n===1?'image':'image2')}")`}} role="img" aria-label={v(n===1?'imageAlt':'image2Alt')}/>)}</div><h1 className={s.voicesTitle}>{t('title')}</h1><div className={s.voices}>{[1,2].filter(n=>n===1||step>0).map(n=><motion.blockquote key={n} initial={still?false:{opacity:0,y:35}} animate={{opacity:n===1&&step?.72:1,y:0}} transition={tr}><span aria-hidden>“</span><p>{t(`item${n}`)}</p></motion.blockquote>)}</div></>;
 if(v('composition')==='knowledge-filter')return <><h1 className={s.filterTitle}>{t('title')}</h1><svg className={s.filterLines} viewBox="0 0 1280 720" aria-hidden><path d="M640 250C640 335 280 270 280 380M640 250C640 335 1000 270 1000 380"/>{step>0&&<motion.path d="M1000 430V485M1000 485H805V540M1000 485V540M1000 485H1160V540" initial={still?false:{pathLength:0}} animate={{pathLength:1}} transition={tr}/>}</svg><div className={s.aiHub}>{t('middleLabel')}</div><div className={s.readers}><article><span>01</span><h2>{t('leftLabel')}</h2><p>{t('leftContext')}</p>{step>0&&<motion.div className={s.plainAnswer} initial={still?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={tr}><span>{t('answerLabel')}</span><h3>{t('leftOutput')}</h3><i/><i/><i/></motion.div>}</article><article><span>02</span><h2>{t('rightLabel')}</h2><p>{t('rightContext')}</p>{step>0&&<motion.div className={s.filters} initial={still?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={tr}>{[1,2,3].map(n=><div key={n}><b>{['?','↔','↗'][n-1]}</b><strong>{t(`filter${n}`)}</strong></div>)}</motion.div>}</article></div><p className={s.filterCaption}>{t(step?'after':'subtitle')}</p></>;
 return <><nav className={s.choiceRail} aria-label="Tre frågor om AI-stödet">{[1,2,3].map(n=><span key={n} data-active={step===n-1}>0{n} {t(`item${n}`)}</span>)}</nav><AnimatePresence mode="wait" initial={false}><motion.section key={step} className={s.choiceScene} initial={still?false:{opacity:0,y:45}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-35}} transition={{duration:still?0:.45,ease:sceneEase}}><div className={s.choiceCopy}><h1>{t(`item${step+1}`)}</h1><p>{t(`detail${step+1}`)}</p></div><div className={s.choiceVisual}><div className={s.assignment}><span>{t('assignmentLabel')}</span><h2>{t('assignmentTitle')}</h2><i/><i/></div>{step===0?<div className={s.knowledgeCards}>{[1,2,3].map(n=><motion.div key={n} initial={still?false:{x:90,opacity:0,rotate:8}} animate={{x:0,opacity:1,rotate:(n-2)*-5}} transition={{...tr,delay:still?0:n*.16}}><span>0{n}</span><h2>{t(`knowledge${n}`)}</h2></motion.div>)}</div>:step===1?<div className={s.timing}><div className={s.timingLine}/>{[1,2,3].map(n=><motion.div key={n} initial={still?false:{y:25,opacity:0}} animate={{y:0,opacity:1}} transition={{...tr,delay:still?0:n*.15}}><i/><strong>{t(`moment${n}`)}</strong></motion.div>)}</div>:<div className={s.supportCycle}><svg viewBox="0 0 570 320" aria-hidden><path d="M90 195Q30 70 230 70H430M430 70Q550 70 520 205H120"/><path d="m405 55 25 15-25 15M145 190l-25 15 25 15"/></svg><div>{t('supportLabel')}</div><div>{t('studentLabel')}</div></div>}</div></motion.section></AnimatePresence></>;
}
