"use client";
import { motion } from 'framer-motion';
import type { ReactNode } from 'react';
import { sceneEase } from '../shared/SceneMotion';
import s from './teaching-design.module.css';
type Props={step:number;still:boolean;v:(key:string)=>string;t:(key:string)=>ReactNode;prompt:()=>ReactNode};
export function TeachingDesign({step,still,v,t,prompt}:Props){
 const tr={duration:still?0:.8,ease:sceneEase};
 if(v('composition')==='pedagogical-responsibility')return <><div className={s.responsibilityGlow}/><svg className={s.responsibilityLines} viewBox="0 0 1280 720" aria-hidden>{[0,1,2].map(i=><motion.path key={i} d={`M${1020+i*55} -40Q${760+i*75} 340 ${990+i*65} 760`} initial={still?false:{pathLength:0}} animate={{pathLength:1}} transition={{duration:still?0:2.2,delay:still?0:i*.18}}/>)}</svg><div className={s.responsibilityCopy}><p>{t('lead')}</p><h1>{t('focusWord')}<motion.strong initial={still?false:{y:60,opacity:0}} animate={{y:0,opacity:1}} transition={tr}>{t('focusTail')}</motion.strong></h1><p>{t('tail')}</p></div></>;
 const phase=Math.max(0,Math.min(2,Number(v('designPhase'))||0));
 return <><p className={s.teacherLabel}>{t('teacherLabel')}</p><nav className={s.roadmap} aria-label="Undervisningens tre delar">{[1,2,3].map(n=><div key={n} data-state={phase===n-1?'active':phase>n-1?'past':'next'}><span>0{n}</span><h2>{t(`stage${n}`)}</h2><i/></div>)}</nav><motion.div className={s.teacherQuestions} key={phase} initial={still?false:{y:25,opacity:0}} animate={{y:0,opacity:1}} transition={tr}><h1>{t('title')}</h1><p>{t('subtitle')}</p>{[1,2,3].map(n=><div key={n}><span>0{n}</span><p>{t(`designQuestion${n}`)}</p></div>)}</motion.div><motion.div className={s.material} initial={false} animate={{x:phase===0?0:phase===1?-15:0,rotate:phase===0?-4:phase===1?-6:-2}} transition={tr}><header>{t('assignmentLabel')}</header><h2>{t('assignmentTitle')}</h2><p>{t('studentBefore')}</p></motion.div>{phase===0?<motion.div className={s.preparation} initial={still?false:{y:40,opacity:0}} animate={{y:0,opacity:1}} transition={tr}><span>{t('preparationLabel')}</span><p>{t('preparationText')}</p></motion.div>:phase===1?<div className={s.conversation}>{step===0?prompt():<motion.div className={s.response} data-chat-answer initial={still?false:{y:30,opacity:0}} animate={{y:0,opacity:1}} transition={tr}><header>{t('responseLabel')}</header><p>{t('response')}</p><small>{t('responseNote')}</small></motion.div>}</div>:<motion.div className={s.followup} initial={still?false:{y:40,opacity:0}} animate={{y:0,opacity:1}} transition={tr}><span>{t('followupLabel')}</span><h2>{t('followupTask')}</h2><p>{t('followupCheck')}</p></motion.div>}</>;
}
